### ISSUE TITLE
Reviewing two Jupyter recipes

### ISSUE THREAD

**Issue by rossant** [ipython-books/recipes-for-review#2]
Hi @minrk @jdfreder @Carreau @blink1073 @ellisonbg

Would you be willing to do a short technical review of these two Jupyter/JupyterLab recipes before Nov 24th for the upcoming IPython Cookbook, 2nd edition? It's just a matter of going through the recipes and let me know of any comments, errors, or things that I forgot to talk about.

If not, could you please let me know of anyone else who might be interested?

Thanks!

* [Configuring the Jupyter notebook](https://github.com/ipython-books/recipes-for-review/blob/master/chapter03/05_custom_notebook.md)
* [Introducing JupyterLab](https://github.com/ipython-books/recipes-for-review/blob/master/chapter03/06_jupyterlab.md)

**Comment by Carreau** [comment]
> Configuring the Jupyter notebook

This part looks got to me, one detail (which may not be worth mentionning

> cat ~/.jupyter/jupyter_notebook_config.py

all `~/.jupyter/*.py` have a `.json` counterpart that can be modified programmatically and take precedence over the `.py` file (for the defined options). For example the `jupyter notebook password` command will set a password in the Json file.

> Introducing JupyterLab

cc @jzf2101

I think you can add one thing: Classic Notebook and lab can be run at the same time (I think lab even have a "Launch Classic notebook Menu). As long as the same file is not open in both. I would also put the section: "JupyterLab uses the exact same notebook server and same notebook format, so that it is fully compatible with the existing notebooks and kernels." At the top. It is one of the most recurrent questions.

**Comment by blink1073** [comment]
Excellent overview, @rossant, thank you!  

cc @afshin @sccolbert

**Comment by jzf2101** [comment]
@rossant looks like a good start.  some of the screecaps are scaled a bit large in my personal opinion.  is it possible to make the scale more true to size?

**Comment by rossant** [comment]
The resolution is high because images will be printed on paper in the book (need for sufficiently high DPI), but they will be much smaller in the book and in the final online version.

**Comment by jzf2101** [comment]
ahhh

**Comment by rossant** [comment]
Thanks @Carreau @blink1073 (and kudos for JupyterLab which is really fantastic)
