### ISSUE TITLE
Reviewing two matplotlib/seaborn recipes

### ISSUE THREAD

**Issue by rossant** [ipython-books/recipes-for-review#4]
Hi @tacaswell @mwaskom

Would you be willing to do a short technical review of these matplotlib/seaborn recipes before Nov 24th for the upcoming IPython Cookbook, 2nd edition? It's just a matter of going through the recipes and let me know of any comments, errors, or things that I forgot to talk about.

If not, could you please let me know of anyone else who might be interested?

Thanks!

* [Using matplotlib styles](https://github.com/ipython-books/recipes-for-review/blob/master/chapter06/01_styles.md)
* [Creating beautiful statistical plots easily with seaborn](https://github.com/ipython-books/recipes-for-review/blob/master/chapter06/02_seaborn.md)

**Comment by mwaskom** [comment]
Some thoughts:

- I would strongly discourage the title. First, "beauty" is always going to be subjective and will rarely if ever be found in defaults, regardless of how tastefully chosen they are. Second, with the default style changes in matplotlib 2.0 and improved stylesheet system, I no longer think of aesthetics as a particularly important motivating factor for using seaborn. I would instead recommend focusing on the dataset-oriented API.

- The introductory text to the seaborn notebook unfairly maligns matplotlib. First, one can write a pure matplotlib script using the object-oriented interface in a way that is much cleaner and more expressive than anything I've seen people accomplish in MATLAB itself, so contrasting "seaborn vs. the worst way of using matplotlib" doesn't seem too useful. Second, code that is "long and tedious" in one context (i.e. exploratory visualization) is "flexible and specific" in another (i.e. in the seaborn internals). I really don't like it when people contrast seaborn and matplotlib by assuming that it's objectively and always better to produce something with less code. To get there, seaborn has to add a lot of constraints and assumptions. They're helpful in some contexts and harmful in others. The way to be helpful to users is not to simply say "matplotlib is tedious" but rather to help them understand the necessary tradeoffs so that they can choose the best tool for a specific task.

- In the seaborn tutorial notebook, your "matplotlib default" plot is certainly *not* the matplotlib default.

- Throughout the notebook, I'd strongly recommend using `plt.subplots()` and explicitly passing Axes objects to seaborn functions, rather than using the `plt.subplot` state machine. Also, in almost all of your multi-panel figures, you should be sharing axes.

- If you are going to show different approaches to visualization distributions (the swam and violin plot example) it would seem to make more sense to plot the same data so that people can appreciate the different perspective the two plots afford.

- The barplot example suggests that only a barplot can be subdivided by a `hue` variable, but that's not the case.

- Apologies if this seems grouchy, but ... these are basically just examples copied from the seaborn documentation with prose that just states what each plot is without giving any deeper consideration.  I gather this is going into some sort of book that people will pay money for? Seaborn has a open, permissive license, so legally that's fine as far as it goes. But I find it irritating when people simply reproduce material that exists for free in documentation without really adding to it and then selling it for profit.

**Comment by rossant** [comment]
Thanks for your comments. Apologies if I didn't introduce the context first: the IPython Cookbook 2nd edition gathers 100+ short recipes showing how to do various tasks with various Python libraries. The book covers a *lot* of different topics and intentionally privileges breadth over depth. The goal is really to show the diversity of the libraries in the SciPy/PyData stack. There is no way I can go deeper on every topic. The goal of this recipe is merely to say (mostly to beginners): "Hey, you probably know matplotlib, but be aware that there are other libraries out there that can might be more relevant to what you're doing."

I get your points about the unfair comparison between matplotlib and seaborn and I'll rework it.

Finally, I find your last comment unfair given that I negotiated with the editor something that they don't do normally, which is release basically the entire book for free with a permissive license to make the broader community benefit from the contents.

**Comment by mwaskom** [comment]
> Finally, I find your last comment unfair given that I negotiated with the editor something that they don't do normally, which is release basically the entire book for free with a permissive license to make the broader community benefit from the contents.

Fair enough, but from my perspective you're getting paid to copy work I (and others) generated without compensation and shared for free (and then asking me to take time out of my own busy schedule to review the work!) I just find it a bit odd. Anyway, good luck...

**Comment by tacaswell** [comment]
- The first image in the style example should probably be the default style. I think `'classic'`, if included as an image at all, should be towards the end or in a footnote.
 - `do_plot` should take in an `Axes` object (see https://matplotlib.org/tutorials/introductory/usage.html#coding-styles )
 - :+1: for showing how to create custom style sheets and use more than 1 at at time.
 - remove https://matplotlib.org/users/style_sheets.html which goes to an old page and may 404 in the near future.
 - I agree with almost everything @mwaskom said, particularly points 1 and 2.  I think the right thing to focus on is the dataframe focused API and the data reduction to make the kinds of plots used in a particular domain easy.  This ties back to https://matplotlib.org/tutorials/introductory/usage.html#coding-styles in that users should be making their own highly tuned mini-libraries.
 - If you are going to mention grammar of graphics you should also link to https://plotnine.readthedocs.io/en/stable/ 
 - It is in the see also, but a a link to  https://altair-viz.github.io/ in the references is probably a good idea.
 - Might be worth adapting the coding style docs to be an additional chapter.

**Comment by rossant** [comment]
Thanks @tacaswell
